FROM solr:8

EXPOSE 8983

ENV SOLR_INSTALL="/opt/solr"
ENV SOLR_CONFIG_DIR="$SOLR_INSTALL/server/solr/configsets"
ENV SOLR_SCHEMA_FILE="$SOLR_CONFIG_DIR/ckan/conf/managed-schema"

ARG JTS_VERSION="1.19.0"
ARG JTS_JAR_FILE="$SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/lib/jts-core-$JTS_VERSION.jar"

ARG IK_VERSION="8.5.0"
ARG IK_JAR_FILE="$SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/lib/ik-analyzer-$IK_VERSION.jar"

USER root

# Create a CKAN configset by copying the default one
RUN cp -R $SOLR_CONFIG_DIR/_default $SOLR_CONFIG_DIR/ckan

# Update the schema
ADD https://raw.githubusercontent.com/depositar/ckanext-data-depositario/master/solr/schema.xml $SOLR_SCHEMA_FILE

# Install JTS JAR file
ADD https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/$JTS_VERSION/jts-core-$JTS_VERSION.jar \
    $JTS_JAR_FILE
RUN chmod 644 $JTS_JAR_FILE

# Install ik-analyzer
ADD https://repo1.maven.org/maven2/com/github/magese/ik-analyzer/$IK_VERSION/ik-analyzer-$IK_VERSION.jar \
    $IK_JAR_FILE
RUN chmod 644 $IK_JAR_FILE
RUN mkdir $SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/classes
ADD https://raw.githubusercontent.com/depositar/ckanext-data-depositario/master/solr/IKAnalyzer.cfg.xml \
    $SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/classes/IKAnalyzer.cfg.xml
RUN chmod 644 $SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/classes/IKAnalyzer.cfg.xml
ADD https://raw.githubusercontent.com/depositar/ckanext-data-depositario/master/solr/dic/words.dic \
    $SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/classes/words.dic
RUN chmod 644 $SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/classes/words.dic

RUN chmod 644 $SOLR_SCHEMA_FILE

USER solr

CMD ["sh", "-c", "solr-precreate ckan $SOLR_CONFIG_DIR/ckan"]
